services:
  mysql:
    container_name: mysql
    build:
      context: ./config/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}

  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: ./config/app/Dockerfile
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
    ports:
      - ${APP_PORT}:${APP_PORT}